# conda env create -f environment.yml
name: aiida-archive-demo
channels:
  - "conda-forge"
dependencies:
- python=3.8
- graphviz
- jupytext
- pip
- pip:
  - git+git://github.com/chrisjsewell/aiida_core@new-archive#egg=aiida-core[atomic_tools]
